-- CD-024 — initial schema for the "postgres" profile.
-- Generated from the JPA entities via Hibernate's PostgreSQL dialect, so the
-- column types match exactly what `ddl-auto: validate` expects (Instant ->
-- timestamp(6) with time zone, byte[] photo -> bytea, identity columns, enums
-- as varchar + CHECK). Seed data (admin + samples) is inserted in Java by
-- DataInitializer, not here.
--
-- Future schema changes go in new V2__*.sql / V3__*.sql files. NOTE: the role /
-- action CHECK constraints below enumerate the Role / AuditAction enum values —
-- adding a new enum value needs a V2 migration to widen the matching CHECK
-- *before* deploying code that writes it (otherwise inserts fail validation).

create table users (
    id                    bigint generated by default as identity,
    username              varchar(255) not null unique,
    password              varchar(255) not null,
    role                  varchar(255) default 'USER' not null
                              check (role in ('USER', 'ADMIN')),
    enabled               boolean default true not null,
    created_at            timestamp(6) with time zone not null,
    failed_login_attempts integer default 0 not null,
    locked_until          timestamp(6) with time zone,
    primary key (id)
);

create table contacts (
    id                 bigint generated by default as identity,
    owner_id           bigint not null,
    first_name         varchar(255) not null,
    last_name          varchar(255) not null,
    email              varchar(255) not null,
    phone              varchar(255),
    company            varchar(255),
    photo              bytea,
    photo_content_type varchar(255),
    favorite           boolean default false not null,
    notes              varchar(4000),
    created_at         timestamp(6) with time zone not null,
    updated_at         timestamp(6) with time zone not null,
    deleted_at         timestamp(6) with time zone,
    version            bigint default 0 not null,
    primary key (id)
);

create table contact_tags (
    contact_id bigint not null,
    tag        varchar(255),
    constraint fk_contact_tags_contact
        foreign key (contact_id) references contacts (id)
);

create table audit_events (
    id          bigint generated by default as identity,
    timestamp   timestamp(6) with time zone not null,
    actor       varchar(255) not null,
    action      varchar(255) not null
                    check (action in (
                        'CONTACT_CREATE', 'CONTACT_UPDATE', 'CONTACT_DELETE',
                        'CONTACT_RESTORE', 'CONTACT_PURGE', 'CONTACT_BULK_DELETE',
                        'CONTACT_BULK_FAVORITE', 'CONTACT_BULK_TAGS', 'CONTACT_IMPORT',
                        'CONTACT_PHOTO_UPDATE', 'CONTACT_PHOTO_DELETE',
                        'USER_ROLE_CHANGE', 'USER_ENABLED_CHANGE', 'USER_PASSWORD_RESET',
                        'USER_DELETE', 'AUTH_REGISTER', 'AUTH_LOGIN', 'AUTH_PASSWORD_CHANGE')),
    target_type varchar(255) not null,
    target_id   bigint,
    summary     varchar(500),
    primary key (id)
);

-- Indexes for the common query paths (owner-scoped lists, trash filtering,
-- newest-first / by-actor audit queries, tag join). Not required by `validate`
-- but good hygiene for the production database.
create index idx_contacts_owner_id   on contacts (owner_id);
create index idx_contacts_deleted_at on contacts (deleted_at);
create index idx_contact_tags_contact on contact_tags (contact_id);
create index idx_audit_events_timestamp on audit_events (timestamp);
create index idx_audit_events_actor     on audit_events (actor);
