-- CD-028 — refresh-token sessions + new audit actions.
--
-- 1) refresh_tokens: one row per issued refresh token. The raw secret is never
--    stored — only its SHA-256 hex — and rotations share a family_id so replay
--    of a stolen token can be detected and the whole family revoked.
-- 2) audit_events.action CHECK: V1 enumerated the AuditAction values, so the
--    two new actions (AUTH_LOGOUT, AUTH_TOKEN_REUSE) need the constraint
--    widened BEFORE code that writes them is deployed (as V1's header warns).

create table refresh_tokens (
    id            bigint generated by default as identity,
    user_id       bigint not null,
    token_hash    varchar(64) not null,
    family_id     varchar(36) not null,
    issued_at     timestamp(6) with time zone not null,
    expires_at    timestamp(6) with time zone not null,
    used_at       timestamp(6) with time zone,
    revoked_at    timestamp(6) with time zone,
    revoke_reason varchar(32),
    primary key (id),
    constraint uq_refresh_tokens_token_hash unique (token_hash),
    constraint fk_refresh_tokens_user foreign key (user_id)
        references users (id) on delete cascade
);

create index idx_refresh_tokens_user_id    on refresh_tokens (user_id);
create index idx_refresh_tokens_family_id  on refresh_tokens (family_id);
create index idx_refresh_tokens_expires_at on refresh_tokens (expires_at);

-- Widen the audit_events action CHECK. The V1 constraint name was generated by
-- Postgres, so look it up from the catalog instead of hard-coding it. Drop EVERY
-- check constraint on the table (schema-qualified to the table's own namespace),
-- so this is deterministic even if more than one ever exists.
do $$
declare
    cname text;
begin
    for cname in
        select c.conname
        from pg_constraint c
        join pg_class t on t.oid = c.conrelid
        join pg_namespace n on n.oid = t.relnamespace
        where t.relname = 'audit_events'
          and n.nspname = current_schema()
          and c.contype = 'c'
    loop
        execute format('alter table audit_events drop constraint %I', cname);
    end loop;
end $$;

alter table audit_events
    add constraint chk_audit_events_action check (action in (
        'CONTACT_CREATE', 'CONTACT_UPDATE', 'CONTACT_DELETE',
        'CONTACT_RESTORE', 'CONTACT_PURGE', 'CONTACT_BULK_DELETE',
        'CONTACT_BULK_FAVORITE', 'CONTACT_BULK_TAGS', 'CONTACT_IMPORT',
        'CONTACT_PHOTO_UPDATE', 'CONTACT_PHOTO_DELETE',
        'USER_ROLE_CHANGE', 'USER_ENABLED_CHANGE', 'USER_PASSWORD_RESET',
        'USER_DELETE', 'AUTH_REGISTER', 'AUTH_LOGIN', 'AUTH_PASSWORD_CHANGE',
        'AUTH_LOGOUT', 'AUTH_TOKEN_REUSE'));
